language: python
python: 2.7

install:
  - pip install ansible

  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"

script:
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
  - "ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo"
