---
# tasks file for ansible-role-pip
- name: Chek if pip is installed
  changed_when: false
  failed_when: false
  command: "which pip"
  register: which_pip
  ignore_errors: yes

- name: Download get-pip.py
  get_url: url=https://bootstrap.pypa.io/get-pip.py dest={{working_directory}}
  when: which_pip.rc == 1

- name: Run get-pip.py
  command: python {{working_directory}}/get-pip.py
  become: yes
  become_method: sudo
  when: which_pip.rc == 1

- name: Remove get-pip.py
  file: path={{working_directory}}/get-pip.py state=absent
  when: which_pip.rc == 1
